In [1]:

carlotte = "1-ZU3bCEGqQ"

# Getting Started
This notebook will help to get stated with techno production. Our first steps are to follow the 8 steps in the polymath module. 

The current steps in the polymath module are:
    - Segmenting the audio file 
    - Getting average pitch and loudness
    - getting song duration 
    - Sample separation 
    - Beat tracking 
    - feature extraction
    - Feature aggregation 
    - Split Stems 

Here we will go through each step and explain what is happening.

## Step 1: Segmenting the audio file
```python 
def get_segments(audio_file):
    from sf_segmenter.segmenter import Segmenter
    segmenter = Segmenter()
    boundaries, labs = segmenter.proc_audio(audio_file)
    return boundaries,labs 
```


In [2]:
import librosa
import numpy as np

# load audio file from the paranet directory of the current directory in polymath library folder
audio_file = "../polymath/library/1-ZU3bCEGqQ.wav"
audio, sr = librosa.load(audio_file)



In [3]:
def get_segments(audio_file):
    from sf_segmenter.segmenter import Segmenter
    segmenter = Segmenter()
    boundaries, labs = segmenter.proc_audio(audio_file)
    return boundaries,labs 

segments_boundaries,segments_labels = get_segments(audio_file)


 > 0
 > 1
 > 2
 > 3
 > 4
 > 5
 > 6
 > 7
 > 8
 > 9
 > 10
 > 11
 > 12
 > 13
 > 14
 > 15
 > 16
 > 17
 > 18
 > 19
 > 20
 > 21
 > 22
 > 23
 > 24
 > 25
 > 26
 > 27
 > 28
 > 29
 > 30
 > 31
 > 32
 > 33
 > 34
 > 35
 > 36
 > 37
 > 38


In [4]:
segments_boundaries

array([   0,   20,   55,   83,  373,  405,  520,  626,  664,  838,  892,
        945,  998, 1103, 1158, 1220, 1249, 1370, 1429, 1539, 1640, 1814,
       1857, 1903, 1956, 2011, 2170, 2231, 2265, 2386, 2438, 2471, 2598,
       2651, 2679, 2808, 2846, 2880, 3077, 3115])

In [5]:
segments_labels


array([0., 1., 1., 1., 1., 1., 1., 2., 2., 1., 1., 1., 1., 1., 1., 3., 1.,
       1., 2., 2., 2., 2., 1., 1., 1., 1., 1., 4., 1., 1., 5., 1., 1., 1.,
       1., 1., 6., 1., 7.])

## Pitch Tracking
Getting average pitch and loudness

Here we first need to figure out what is the pitch of a song. We do use a Neural network called crepe to do this. We will use the crepe module to do this. 



```python
def get_pitch_dnn(audio_file):
    # DNN Pitch Detection
    pitch = []
    audio, sr = librosa.load(audio_file)
    time, frequency, confidence, activation = crepe.predict(audio, sr, model_capacity="tiny", viterbi=True, center=True, step_size=10, verbose=1) # tiny|small|medium|large|full
    i = 0
    while i < len(time):
        pitch.append([time[i],frequency[i],confidence[i]])
        i += 1
    return pitch
```

    

In [4]:
import crepe

def get_pitch_dnn(audio_file):
    # DNN Pitch Detection
    pitch = []
    audio, sr = librosa.load(audio_file)
    time, frequency, confidence, activation = crepe.predict(audio, sr, model_capacity="tiny", viterbi=True, center=True, step_size=10, verbose=1) # tiny|small|medium|large|full
    i = 0
    while i < len(time):
        pitch.append([time[i],frequency[i],confidence[i]])
        i += 1
    return pitch

frequency_frames = get_pitch_dnn(audio_file)



: 

: 

In [ ]:
average_frequency,average_key = get_average_pitch(frequency_frames)

IndexError: invalid index to scalar variable.

In [7]:
segments_boundaries

array([   0,   20,   55,   83,  373,  405,  520,  626,  664,  838,  892,
        945,  998, 1103, 1158, 1220, 1249, 1370, 1429, 1539, 1640, 1814,
       1857, 1903, 1956, 2011, 2170, 2231, 2265, 2386, 2438, 2471, 2598,
       2651, 2679, 2808, 2846, 2880, 3077, 3115])

In [9]:
sr

22050

In [32]:
import soundfile as sf
import IPython.display

# generate a default beat of length 10 seconds at 22050 Hz sampling rate 
beat = librosa.clicks(frames=np.arange(0, 1000), sr=100000, length=1000)

# save the beat to a file
sf.write('beat.wav', beat, sr)

# play the beat
IPython.display.Audio('beat.wav')

In [15]:
librosa.__version__

'0.9.2'

In [3]:
import numpy as np
import matplotlib.pyplot as plt

